# Generated by Django 3.1.6 on 2021-07-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yearTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='membersRobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('President', 'President'), ('Vice-President', 'Vice-President'), ('General Secretriat', 'General Secretriat'), ('Treasurer', 'Treasurer'), ('Member', 'Member')], default='General Member', max_length=30)),
                ('yearMembership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.yearteam')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
