# Generated by Django 3.1.6 on 2021-07-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearteam',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
